### ISSUE TITLE
Export "@frontify/arcade/foundation"?

### ISSUE THREAD

**Issue by getflourish** [Frontify/arcade#578]
Hi! I’m using Arcade for the first time and was wondering how to import components from the Foundation, e.g .`Heading` and `Text`. I noticed that all other components are exported in `package.json` but not the Typography Foundation. What’s the recommended approach to use those? Would it make sense to export those, too?

https://github.com/Frontify/arcade/blob/main/package.json

How package.json looks like:

```
"./components/*": {
    "types": "./dist/src/components/*/index.d.ts",
    "import": "./dist/src/components/*/index.js"
}
...
```

What I need:

```
"./components/*": {
    "types": "./dist/src/components/*/index.d.ts",
    "import": "./dist/src/components/*/index.js"
},
"./foundation/*": {
    "types": "./dist/src/foundation/*/index.d.ts",
    "import": "./dist/src/foundation/*/index.js"
},
```

→ Usage:

```
import { Heading } from '@frontify/arcade/foundation/typography/Heading';
```

**Comment by getflourish** [comment]
Nevermind, importing anything from `@frontify/arcade` seems to work just fine. The issue might have been related to the specific Webpack setup.

**Comment by SamuelAlev** [comment]
We still have some issues with treeshaking and `sideEffects`, a bugfix is being made and we will remove the `exports` list to avoid confusion.
