### ISSUE TITLE
Stack: "spacing" prop has no effect

### ISSUE THREAD

**Issue by getflourish** [Frontify/arcade#580]
Using the `spacing` prop on a `Stack` component has no visual effect. A class is correctly applied, e.g. `tw-gap-small`, but there’s no defined CSS Class that would actually change the value for the `gap` property. 
For reference: https://arcade-components.frontify.com/?path=/docs/foundation-layout-stack--default

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/183989/151834050-2b144ddb-7395-41ec-a013-0f5142374c62.png">

**Comment by SamuelAlev** [comment]
Hello, thanks for raising the issue, it has been fixed on `main` (https://github.com/Frontify/arcade/commit/bbd162934ed3c6c29686fe761b16a4fddad7f917), a release will be done in the upcoming days.

The `spacing` prop will accept `"none" | "xxs" | "xs" | "s" | "m" | "l" | "xl" | "xxl"`.
