### ISSUE TITLE
Flyout: Transparent Trigger?

### ISSUE THREAD

**Issue by getflourish** [Frontify/arcade#597]
When passing a `<Button>` as trigger prop to a `Flyout` the trigger gets wrapped in a pseudo button element with `-webkit-appearance: button`. This means, that if the render prop has a border radius, e.g. as seen in the standard `<Button>`, that there will be a visual glitch where the wrapping div shows a visible background color at the corners:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/183989/152968802-48fddf37-21e7-43e2-934c-7680e50fca73.png">

**Comment by SamCreasey** [comment]
@getflourish This issue has now been fixed and will be included in the next release of arcade :)
When using a button trigger you now have the option to pass a render-function to the trigger prop. This provides an alternative where you can add the ref and props to your own component without the wrapping div. For examples please checkout the storybook code. Note: This will also fix the spacing issue with the additional margin being automatically applied to the trigger container
