### ISSUE TITLE
Breadcrumbs: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

### ISSUE THREAD

**Issue by getflourish** [Frontify/arcade#645]
When the `items` prop of the Breadcrumb component changes its value, React crashes with the following error:

`Rendered fewer hooks than expected. This may be caused by an accidental early return statement.`

This is most likely because `useRef` is used inside the rendering which will result in different amount/order of hooks. 

**Reproduction**

The reproduction shows:

- Breadcrumbs with initial state
- useEffect changes the state → error

https://codesandbox.io/s/breadcrumbs-tabindex-frontify-arcade-2-3-0-forked-c0vklv?file=/src/App.js

**Comment by getflourish** [comment]
Problematic line of code:
https://github.com/Frontify/arcade/blob/bd063b8856999bb244f03df6e24c8cc5f8d4b23c/src/components/Breadcrumbs/Breadcrumbs.tsx#L41

**Comment by deniaz** [comment]
Hey @getflourish 

Thanks for the report. We had the issue already in other places and I'll have a look at it. 😄

**Comment by getflourish** [comment]
Thanks for looking into it @deniaz!
