### ISSUE TITLE
MenuItem: How to use onClick?

### ISSUE THREAD

**Issue by getflourish** [Frontify/arcade#700]
The docs for the MenuItem show a onClick prop:
https://arcade-components.frontify.com/?path=/docs/components-menu-item--menu-item

But when I try to use it, it doesn't work. How do I use the MenuItem with a callback function?

**Reproduction:**
https://codesandbox.io/s/menuitem-frontify-arcade-2-0-0-3jet0z

**Comment by jonasbuechel** [comment]
closed by #725
